spring.application.name=lab7
server.port=8080
spring.mvc.servlet.path=/
spring.profiles.active=dev

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.persistAuthorization=true
springdoc.swagger-ui.displayRequestDuration=true
springdoc.swagger-ui.show-common-extensions=true
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true
springdoc.swagger-ui.oauth.client-id=lab7-client
springdoc.swagger-ui.oauth.scopes=openid,profile
springdoc.swagger-ui.oauth2-redirect-url=http://localhost:8080/swagger-ui/oauth2-redirect.html


# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/customer_orders
spring.datasource.username=postgres
spring.datasource.password=1
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Liquibase
liquibase.secureParsing=false
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/changelog.xml
spring.jpa.open-in-view=false

# JWT
jwt.secret=FWE325942HUF2Fh3grgj26575UFWHEu234676g
auth.service.url=http://localhost:8081/auth



# Keycloak Server
keycloak.auth-server-url=http://localhost:8081
keycloak.realm=lab10-realm
keycloak.resource=lab10-client
keycloak.public-client=true
keycloak.principal-attribute=preferred_username

spring.security.oauth2.resourceserver.jwt.issuer-uri=${keycloak.auth-server-url}/realms/${keycloak.realm}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs

## Keycloak Admin
keycloak.admin-client.server-url=${keycloak.auth-server-url}
keycloak.admin-client.realm=master
keycloak.admin-client.client-id=admin-cli
keycloak.admin-client.username=admin
keycloak.admin-client.password=admin
keycloak.admin-client.client-secret=zolLlkeu2rxuzoAojywFJviGLyol03mJ
#keycloak.admin-client.grant-type=password