spring.application.name=security
server.port=8081

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/customer_orders
spring.datasource.username=postgres
spring.datasource.password=1
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Liquibase
liquibase.secureParsing=false
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/changelog.xml
spring.jpa.open-in-view=false

# JWT
jwt.secret=FWE325942HUF2Fh3grgj26575UFWHEu234676g
jwt.expiration=3600000